baseurl = "https://verana.foundation"
enableGitInfo = true
DefaultContentLanguage = "en"
title = "Verana Foundation"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
  commit = "https://github.com/verana-labs/verana.foundation-website/tree/"
  homeTitle = "Verana Foundation" # Set a different text for the header on the home page
  subtitle = "To empower digital trust and privacy by developing open standards, decentralized infrastructure, and transparent governance frameworks that enable secure, verifiable, and user-controlled interactions across the digital world"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = false
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[[Params.bigimg]]
  src = "img/triangle.jpg"
#  desc = "Triangle"
[[Params.bigimg]]
  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
[[Params.bigimg]]
  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Verana Foundation"
  website = "verana.foundation"
  github = "verana-labs"
 # twitter = "username"
 # reddit = "username"
 # linkedin = "username"
 # slack = "username"
 # medium = "username"
 # discord = "invite code (https://discord.gg/XXXXXXX)"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1



[[menu.main]]
    name = "Learn"
    url = "page/learn/"
    weight = 3

[[menu.main]]
    name = "Why we need Verifiable Trust"
    url = "page/learn-vt-why/"
    weight = 20
    parent = "Learn"

[[menu.main]]
    name = "Verifiable Trust Demystified"
    url = "page/learn-vt-demystified/"
    weight = 25
    parent = "Learn"

[[menu.main]]
    name = "Business Models"
    url = "page/learn-vt-business-models/"
    weight = 30
    parent = "Learn"

[[menu.main]]
    name = "Trust Deposit & Reputation"
    url = "page/learn-vt-trust-deposit-and-reputation/"
    weight = 35
    parent = "Learn"

[[menu.main]]
    name = "Essential Credential Schemas"
    url = "page/learn-vt-essential-credential-schemas/"
    weight = 37
    parent = "Learn"

[[menu.main]]
    name = "Service Directory and Search Engine"
    url = "page/learn-vt-service-directory/"
    weight = 40
    parent = "Learn"

[[menu.main]]
    name = "Use Cases"
    url = "page/learn-vt-usecases/"
    weight = 45
    parent = "Learn"


[[menu.main]]
    name = "Deliverables"
    url = "page/deliverables/"
    weight = 4

[[menu.main]]
    name = "Network"
    url = "page/network/"
    weight = 7
